### PR TITLE
fix layer bug

### LINKED ISSUE #106: layer() fails to group more then 2 plots
``` julia
using Vega
layer(layer(scatterplot(x=[1],y=[1]), scatterplot(x=[2],y=[2])), scatterplot(x=[3],y=[3]))
```
returns a not rendering vega plot :(

### PR DESCRIPTION
**Pull request by panlanfeng**
There is a bug in `layer` with `domain` if adding together more than 2 layers. This fixed #106 
After this PR, the following should work

~~~julia
using Distributions
using Vega
N=500
x = sort(randn(N));
xeval=linspace(-5,5,200);
yden=pdf(Normal(),xeval);

#v1=histogram(x=x,relativefreq=true,bandwidth=0.2);
v2=lineplot(x=xeval,y=yden);
v3=rugplot(x=x)
v4=scatterplot(x=xeval,y=yden)

v2+v3+v4
~~~

After PR #141 , the histogram layer works as well.

There are still some other problems with layer, such as setting the colors. This needs some more work.

### CODE REVIEW

File: src/intermediates/layer.jl [hunk 1]
```diff
@@ -32,9 +32,36 @@ function layer(plot1::VegaVisualization, plot2::VegaVisualization)
...
+        [ydomain1, ydomain2;])
 
     return baseplot
 
-end
\ No newline at end of file
+end
+
+import Base.+
++(plot1::VegaVisualization, plot2::VegaVisualization)=layer(plot1,plot2)
```
Comment (randyzwitch) [inline src/intermediates/layer.jl]: If you're suggesting adding this as a feature, could you put it into a separate PR for discussion? I'm generally against this type of syntax (1) because I don't like ggplot style syntax and 2) more theoretically I'm not sure this operation is really a commutative one (though, I don't know that it isn't either).

**Comment by randyzwitch** [comment]
Going to merge this, your example works.

There's clearly more work to be done, not only with the colors, but also merging different types of graphs. Pretty sure that different X axis types wont' work.
